name: Build public image

on:
  workflow_call:
    inputs:
      cloud-provider:
        required: false
        type: string
        default: local
      metadata:
        required: false
        type: string
        default: "[ orphan ]"
      host:
        required: false
        type: string
        default: 'test.connectorsapp.com'
      host-path:
        required: false
        type: string
        default: '/'
      port:
        required: false
        type: string
        default: '8080'
      registry:
        required: false
        type: string
        default: 'docker.io'
    secrets:
      cloud-token:
        required: false
      github-token:
        required: false
      dockerhub_username:
        required: false
      dockerhub_token:
        required: false
      db_token:
        required: false
      image-username:
        required: false
      image-pwd:
        required: false

jobs:
  build-public-image:
    runs-on: ubuntu-22.04
    steps:
    
      - uses: actions/checkout@v4

      - name: list files
        run: |
          echo "----------in build-public-image -----------"
          ls -la
          echo "---------------------"

      - name: 3. validate Dockerfile
        id: validate-dockerfile
        run: |
          if [ -e Dockerfile ] 
          then
            echo "EXIST_DOCKERFILE='ok'" >> $GITHUB_OUTPUT
          else
            echo "EXIST_DOCKERFILE='dont'" >> $GITHUB_OUTPUT
          fi

      - name: 4. Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 5. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 6. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      - name: 8. Build and push
        if: contains(steps.validate-dockerfile.outputs.EXIST_DOCKERFILE, 'ok')
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          tags: |
            yabinm/${{ github.event.repository.name }}-img:${{github.sha}}
            yabinm/${{ github.event.repository.name }}-img:latest

      - name: 9. Build and push Docker images with Nixpacks
        if: contains(steps.validate-dockerfile.outputs.EXIST_DOCKERFILE, 'dont')
        uses: iloveitaly/github-action-nixpacks@main
        with:
          cache: true
          cache_tag: docker.io/yabinm/${{ github.event.repository.name }}-img:latest
          push: true
          platforms: "linux/amd64,linux/arm64,linux/arm64/v8"
          tags: |
            docker.io/yabinm/${{ github.event.repository.name }}-img:${{github.sha}}
            docker.io/yabinm/${{ github.event.repository.name }}-img:latest
