name: Deploy using connectors monkey

on:
  workflow_call:
    inputs:
      cloud-provider: 
        required: false
        type: string
        default: local
      metadata:
        required: false
        type: string
        default: "[ orphan ]"
      host: 
        required: false
        type: string
        default: '/'
    secrets:
      cloud-token:
        required: false
      github-token:
        required: false
      dockerhub_username:
        required: false
      dockerhub_token:
        required: false

jobs:      
  build-local:
    runs-on: ubuntu-22.04
    if: inputs.cloud-provider == 'local' 
        
    steps:
              
      - name: local condition
        run: | 
          echo ${{ inputs.cloud-provider }}     
                  
  build-civo:
    runs-on: ubuntu-22.04
    if: inputs.cloud-provider == 'civo'

    steps:      
      - name: civo conditions
        run: |
          echo ${{ inputs.cloud-provider }}

#     1. build repo with Dockerfile
      
      - uses: actions/checkout@v4

      
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.dockerhub_username }}
#          password: ${{ secrets.dockerhub_token }}

#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: yabinm/app:${{github.sha}}

#      - name: docker ps
#        run: |
#          docker image ls
#          docker ps
#          ls

#     2. clone & exec helm
      - name: clone and exec helm
        id: exist-repo
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          echo "EXIST_REPO_1=$(gh repo view snow-monkeys-org/helm-template)" >> $GITHUB_OUTPUT
          echo "EXIST_REPO_2=$(gh repo view snow-monkeys-org/${{ github.event.repository.name }}-helm-civo)" >> $GITHUB_OUTPUT

      
#     if repo already exist
      - name: repo already exist for helm
        if:  ${{ steps.exist-repo.outputs.EXIST_REPO_1 }}
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          echo "repo1 already exist ${{ steps.exist-repo.outputs.EXIST_REPO_1 }}"
          echo "repo2 doesnt exist ${{ steps.exist-repo.outputs.EXIST_REPO_2 }}"

      - name: not exec
        if:  ${{ ! steps.exist-repo.outputs.EXIST_REPO_1 }}
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          echo "not exec"
          

#     if repo doesnt exist
#      - name: repo doesnt exist for helm
#     env:
#     GH_TOKEN: ${{ secrets.github-token }}
#     run: |
#  echo repo already exist ${{ env.EXIST_REPO }}
        
