name: Deploy using connectors monkey

on:
  workflow_call:
    inputs:
      cloud-provider: 
        required: false
        type: string
        default: local
      metadata:
        required: false
        type: string
        default: "[ orphan ]"
      host: 
        required: false
        type: string
        default: '/'
    secrets:
      cloud-token:
        required: false
      github-token:
        required: false
      dockerhub_username:
        required: false
      dockerhub_token:
        required: false
        
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:      
  build-local:
    runs-on: ubuntu-22.04
    if: inputs.cloud-provider == 'local' 
        
    steps:
              
      - name: local condition
        run: | 
          echo ${{ inputs.cloud-provider }}     
                  
  build-civo:
    runs-on: ubuntu-22.04
    if: inputs.cloud-provider == 'civo'

    steps:      
      - name: civo conditions
        run: |
          echo ${{ inputs.cloud-provider }}

#     1. build repo with Dockerfile
      
      - uses: actions/checkout@v4

      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: yabinm/app:${{github.sha}}

      - name: docker ps
        run: |
          docker image ls
          docker ps

      
#      - name: connect to civo kubernetes
#        run: |
#          curl -sL https://civo.com/get | sh
#          civo apikey add my-cluster ${{ secrets.cloud-token }}
#          civo kubernetes config k8s_demo_1 --save
#          kubectl cluster-info
#          kubectl apply -f repo-creds.yaml
#          kubectl apply -f application.yaml

#      - name: create new repo for civo
#        run: |
#          echo "promoting into dev environment"
#          git config --global user.email yabin.monroy.1@gmail.com && git config --global user.name yabinboxes
#          echo "cloning config repo java-test"
#          ls
#          git clone https://oath2:${{ secrets.github-token }}@github.com/yabinboxes/java-test.git
#          cd java-test
#          ls
#          echo "checkout main branch"
#          git checkout main
#          echo "updating image tag in values file"
#          sed -i "s,tag:.*,tag:\ ${{ github.sha }}," myapp-helm/values.yaml
#          git add . && git commit -m "update image tag"
#          git push
         